services:
  redis:
    image: redis:alpine
    container_name: paygate-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    image: pulkitxr/major_project-backend:latest
    container_name: paygate-backend
    ports:
      - "50002:50002"
    environment:
      - REDIS_URL=redis://redis:6379
      - GRPC_PORT=50002
      - Db=mongodb+srv://pulkittales12_db_user:BGvisZXQIpK1Penc@majorproject.uzl2v4i.mongodb.net/payment_gateway_hub
      - JWT_SECRET=PK8UBB
      - WEBHOOK_SIGNING_SECRET=Xmac
    depends_on:
      redis:
        condition: service_healthy

  backend1:
    image: pulkitxr/major_project-backend1:v6
    container_name: paygate-backend1
    ports:
      - "50051:50051"
    environment:
      - REDIS_URL=redis://redis:6379
      - GRPC_PORT=50051
      - Db=mongodb+srv://pulkittales12_db_user:BGvisZXQIpK1Penc@majorproject.uzl2v4i.mongodb.net/payment_gateway_hub
      - ENCRYPTION_KEY=306edd896da862db417378a7aafb6a255191651c6e1281a7a7f2a79b9476ecf2
      - RAZORPAY_WEBHOOK_SECRET=Xmac
      - RAZORPAY_KEY_ID=rzp_test_Rqeqwh3jxZUoO6
      - RAZORPAY_KEY_SECRET=MQCPqJ2mZrw822aXYquwq4a1
    depends_on:
      redis:
        condition: service_healthy

  backend2:
    image: pulkitxr/major_project-backend2:v1
    container_name: paygate-backend2
    ports:
      - "4000:4000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=4000
      - Db=mongodb+srv://pulkittales12_db_user:BGvisZXQIpK1Penc@majorproject.uzl2v4i.mongodb.net/payment_gateway_hub
      - WEBHOOK_SIGNING_SECRET=Xmac
    depends_on:
      redis:
        condition: service_healthy

  apigateway:
    image: pulkitxr/major_project-apigateway:v8
    container_name: paygate-apigateway
    ports:
      - "6283:6283"
    environment:
      - REDIS_URL=redis://redis:6379
      - MERCHANT_GRPC_URL=backend:50002
      - PAYMENT_GRPC_URL=backend1:50051
      - WEBHOOK_SERVICE_URL=http://backend2:4000
      - ALLOWED_ORIGINS=http://localhost:5173
      - JWT_SECRET=PK8UBB
      - SESSION_SECRET=XBSHHDHGHDHD
    depends_on:
      - backend
      - backend1
      - backend2
      - redis

  frontend:
    image: pulkitxr/major_project-frontend:latest
    container_name: paygate-frontend
    ports:
      - "5173:80"
    depends_on:
      - apigateway
